name: ESP-IDF CI

permissions:
    pages: write
    id-token: write

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install ESP-IDF dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git wget flex bison gperf python3 python3-pip python3-setuptools cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0

      - name: Set up ESP-IDF
        run: |
          git clone --recursive https://github.com/espressif/esp-idf.git
          cd esp-idf
          ./install.sh
          . ./export.sh
        shell: bash

      - name: Build ESP-IDF Project
        run: |
          . ./esp-idf/export.sh
          idf.py set-target esp32
          idf.py build
        shell: bash

      - name: Upload artifact 
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/*.bin

      - name: Upload GitHub Page Artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release' && github.event.action == 'created'
    steps:
      - name: Print GitHub event name
        run: |
          echo "${{ github.event_name }}"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4